node_js:
- "5.0"
language: node_js
env:
- COVERALLS_REPO_TOKEN="ckvmICpF1SAKEEXWuEr7zFuV34fKi01LR"
before_script:
- npm install -g istanbul
- npm install -g mocha
- npm install -g gulp
script: gulp cs
